Improve functions returning const int * pointer
APTG/libdedx pull request #15
Opened 2021-11-02 20:53 UTC by piotrpolec

Initial work of dealing with #13

2021-11-09 13:01 UTC, grzanka commented on libdedx/dedx.h
> +//const int * dedx_get_ion_list(int program);
```suggestion
```

remove that

2021-11-11 21:01 UTC, grzanka requested changes
see comments

2021-11-11 21:01 UTC, grzanka commented on libdedx/dedx.c
> +void dedx_get_material_list(int *material_list, int program) {
It's better to put "in" arguments first, and "out" arguments last
```suggestion
void dedx_get_material_list(int program, int *material_list) {
```

2021-11-11 21:01 UTC, grzanka commented on libdedx/dedx.c
> +void dedx_get_ion_list(int * ion_list, int program) {
```suggestion
void dedx_get_ion_list(int program, int * ion_list) {
```

2021-11-11 21:01 UTC, grzanka commented on libdedx/dedx.h
> +void dedx_get_material_list(int * material_list, int program);
```suggestion
void dedx_get_material_list(int program, int * material_list);
```

2021-11-11 21:01 UTC, grzanka commented on libdedx/dedx.h
> +void dedx_get_ion_list(int * ion_list, int program);
```suggestion
void dedx_get_ion_list(int program, int * ion_list);
```

2021-11-11 21:14 UTC, piotrpolec commented on libdedx/dedx.c
> +	dedx_get_ion_list(ion_list, prog);
```suggestion
	dedx_get_ion_list(prog, ion_list);
```

2021-11-12 09:20 UTC, grzanka approved these changes
looks good

2021-11-12 09:55 UTC, merged